version: '2'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ports:
      - 9200:9200
    environment:
      - cluster.name=test
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.publish_host=es
      - discovery.type=single-node
      - cluster.routing.allocation.disk.watermark.flood_stage=99%
